markes=[]
f1=int(input('enter the markes :'))
markes.append(f1)
f2=int(input("enter the the markes :"))
markes.append(f2)
f3=int(input('enter the markes :'))
markes.append(f3)
f4=int(input("enter the the markes :"))
markes.append(f4)
f5=int(input('enter the markes :'))
markes.append(f5)
f6=int(input("enter the the markes :"))
markes.append(f6)
f7=int(input("enter the  mrkes :"))
markes.append(f7)
markes.sort()
print("the total marek is :",markes)

